#!/bin/bash

# ncid-xmpp
# usage: ncid --no-gui --program ncid-xmpp


# Module should should provide a default for all cariables.
# User changable variables are in /etc/ncid/conf.d/ncid-xmpp.conf

# input is always 7 lines
#
# if input is from a call:
# input: DATE\nTIME\nNUMBER\nNAME\nLINE\nTYPE\n\MISC\n
#
# if input is from a message
# the message is in place of NAME:
# input: DATE\nTIME\nNUMBER\nMESG\nLINE\nTYPE\nNAME\n


# look up name of caller
lookupname () {
	if [ -f "$phonebook" ]; then
		entry=$(grep "$1" $phonebook)
		if [ ! -z "$entry" ]; then
			res=$(echo $entry | cut -d' ' -f2-)
			echo -n $res
			return 0
		else
			echo "$1 $2" >> $phonebook
		fi
	else
		echo "$1 $2" >> $phonebook
	fi
	echo -n $2
}

ConfigDir=/etc/ncid/conf.d
ConfigFile=$ConfigDir/ncid-xmpp.conf

# default (see ncid-xmpp.conf for description):
event_types="CID"
# default xmpp JID's to send messages to [seperated by spaces]
xmpp_jids=''

# default sendxmpp TLS flag
xmpp_tls=1
# default sendxmpp user JID
#xmpp_user=
# default sendxmpp password
#xmpp_pass=

phonebook=~/.ncid-numbers.txt
logfile=~/.ncid-calls.txt


[ -f $ConfigFile ] && . $ConfigFile

read DATE
read TIME
read NMBR
read VAR1
read LINE
read TYPE
read VAR2

echo -e "$DATE\n$TIME\n$NMBR\n$VAR1\n$LINE\n$TYPE\n$VAR2" > smp.txt

# Look for $TYPE
for i in $event_types; do
    [ $i = "$TYPE" ] && { found=1; break; }
done


# Exit if $TYPE not found
[ -z "$found" ] && exit 0


# resolve ortsnetzkennzahl from AVON ortsnetzkennzahlenverzeichnis
for i in 3 4 5 6; do
	m=$(grep "^${NMBR:0:$i}\s\s*\S.*" avon.txt)
	if [ -z "$DIST" ] && [ ! -z "$m" ]; then
		DIST=$(echo "$m" | cut -f2-)
		break
	fi
done

if [ "$TYPE" = "MSG" -o "$TYPE" = "NOT" ]
then
    NAME=$(lookupname $NMBR "$VAR2")
    MESG="$VAR1"
    # Display Message or Notice
    notification="$DATE $TIME, $NMBR ($NAME$([ ! -z "$DIST" ] && echo , $DIST)), $TYPE" 
    notification="$notification\n$MESG"
else
    NAME=$(lookupname $NMBR "$VAR1")
    # Display Caller ID information
    notification="Incoming call: $NAME ($NMBR$([ ! -z "$DIST" ] && echo , $DIST)), $DATE $TIME"
fi

xmpp_options="$([ $xmpp_tls = 1 ] && echo -t) $([ ! -z $xmpp_user ] && echo -u  $xmpp_user) \
$([ ! -z $xmpp_pass ] && echo -p $xmpp_pass)"

# log call
echo "$notification" >> $logfile

#[ ! -z $xmpp_user ] && su $xmpp_user
for jid in $xmpp_jids; do
	echo "$notification" | sendxmpp $xmpp_options $jid
done
#[ ! -z $xmpp_user ] && su exit



exit 0
