#!/bin/sh

# ncid-xmpp
# usage: ncid --no-gui --program ncid-xmpp


# Module should should provide a default for all cariables.
# User changable variables are in /etc/ncid/conf.d/ncid-xmpp.conf

# input is always 7 lines
#
# if input is from a call:
# input: DATE\nTIME\nNUMBER\nNAME\nLINE\nTYPE\n\MISC\n
#
# if input is from a message
# the message is in place of NAME:
# input: DATE\nTIME\nNUMBER\nMESG\nLINE\nTYPE\nNAME\n

ConfigDir=/etc/ncid/conf.d
ConfigFile=$ConfigDir/ncid-xmpp.conf

# default (see ncid-xmpp.conf for description):
event_types="CID"
# default xmpp JID's to send messages to [seperated by spaces]
xmpp_jids=""

# default sendxmpp TLS flag
xmpp_tls=1
# default sendxmpp user JID
#xmpp_user=
# default sendxmpp password
#xmpp_pass=


[ -f $ConfigFile ] && . $ConfigFile

read DATE
read TIME
read NMBR
read VAR1
read LINE
read TYPE
read VAR2

# Look for $TYPE
for i in $event_types
do
    [ $i = "$TYPE" ] && { found=1; break; }
done

#echo $TYPE
#echo $xmpp_jids

# Exit if $TYPE not found
[ -z "$found" ] && exit 0

if [ "$TYPE" = "MSG" -o "$TYPE" = "NOT" ]
then
    NAME="$VAR2"
    MESG="$VAR1"
    # Display Message or Notice
    notification="$DATE $TIME, $NMBR ($NAME), $TYPE" 
    notification="$notification\n$MESG"
else
    NAME="$VAR1"
    # Display Caller ID information
    notification="$DATE $TIME, $NMBR ($NAME), $TYPE"
fi

xmpp_options="$([ $xmpp_tls = 1 ] && echo '-t') $([ ! -z $xmpp_user ] && echo '-u' $xmpp_user) \
$([ ! -z $xmpp_pass ] && echo '-p' $xmpp_pass)"

#[ ! -z $xmpp_user ] && su $xmpp_user
echo "Incoming call: $notification" | sendxmpp "$xmpp_options" "$xmpp_jids"
#[ ! -z $xmpp_user ] && su exit

#echo $notification >> .ncid-xmpp.txt
#echo $xmpp_options >> .ncid-xmpp.txt
#echo $xmpp_jids >> .ncid-xmpp.txt

exit 0
